### ISSUE TITLE
Pass options through query parameters

### ISSUE THREAD

**Issue by naitian** [MichiganDaily/cookie#11]
It'd be useful to specify options like "show hed", "show byline", "homepage styles" (#10) as query parameters in the embed URL.

It might also be useful to be able to pass arbitrary parameters outside of that for misc customizations that we might want to make for specific graphics.

**Comment by erxclau** [comment]
> What would be totally rad (but we don't need to do because there are a lot of details to iron out) is if we had a single graphic for bar chart that we could plug in arbitrary data with datagraphics.michigandaily.com/barchart/?data=https://link.to.data.com

For context if/when we get to this, @Aditya-Singhvi did [something like](https://github.com/MichiganDaily/MarchMadnessBracket2022/blob/main/src/graphic/js/graphic.js#L373-L398) this for [March Madness predictions](https://www.michigandaily.com/sports/mens-basketball/daily-basketball-beat-predicts-march-madness-men/) earlier this year.

**Comment by erxclau** [comment]
Curious if there's a neat way to do this with Nunjucks or Parcel involved. It'd be pretty simple to just do this in the client JS but I feel like there could be a few milliseconds of showing the hed or byline or wrong font styles if this is through a JS solution.

**Comment by erxclau** [comment]
One potential thing that could happen with query parameters controlling showing headline and byline is a flash of content that gets hidden.

**Comment by erxclau** [comment]
I'm seeing some more reason to do this for screenshots... if we ever want to extract just a graphic (minus the hed, dek, etc.).
