### ISSUE TITLE
Add social image download option

### ISSUE THREAD

**Issue by naitian** [MichiganDaily/cookie#8]
Use something like [`html-to-image`](https://www.npmjs.com/package/html-to-image) to have an option of downloading the graphic as an image (maybe add this as a button in the wrapper).

1. We could generate this client side on button press or
2. We could generate this at build time or
3. We could do both??

The first option has the advantage of being able to download the most up-to-date graphic in case the data changes.

The second option has the advantage of not needing to generate the same image more than once and having a statically hosted image we can use elsewhere (like in a portfolio site and the **README**).

The third option is obviously the best of both worlds, but might require some clever structuring so we don't have repeated code... (Or we could live with some repeated code)

**Comment by erxclau** [comment]
> The third option is obviously the best of both worlds, but might require some clever structuring so we don't have repeated code... (Or we could live with some repeated code)

@naitian Did you foresee that we could use `html-to-image` for both client and build time image generation? I'm feeling like that package is just for client-side stuff. I think we'd need to bring in something like [`node-html-to-image`](https://github.com/frinyvonnick/node-html-to-image) or [`phantomjs`](https://github.com/ariya/phantomjs) or roll our own headless browser flow. [JSDOM](https://github.com/jsdom/jsdom)? Might be missing something obvious though.

**Comment by naitian** [comment]
Yeah, I wasn't sure about the implementation for doing both client and build... I think you're probably right.

**Comment by erxclau** [comment]
So much for _bite-sized_ if we add a headless browser to cookie 😭. Wondering if those packages will add a new browser install in each instance or if we can get away with trying to point to a browser path outside of the repository.

**Comment by erxclau** [comment]
For build images, we probably want to generate images for both mobile and desktop size screens.

**Comment by naitian** [comment]
One possibility that would maybe add some complexity but alleviate the need to add a browser: we can set up a service that generates these images, instead of doing it locally. Maybe even a github action that adds the images on push?

**Comment by naitian** [comment]
I think we def shouldn't bundle a headless browser lol.

**Comment by erxclau** [comment]
GitHub Actions would we cool. I _just_ merged #38 that ignores data files by default, which poses some authentication problems if we do anything non-locally like GitHub Actions or a Lambda.

I think ignoring data files is _generally_ a good idea but willing to revert (for the following reasons and because it'd probably make a non-local solution to this issue easier). 

1. My motivation for ignoring data files was concerning a graphic @mattbilik is working on that has some semi-sensitive data. On thinking about this more, maybe that shouldn't be handled at the `.gitignore` level, but rather at the this-spreadsheet-shouldn't-have-anything-sensitive-to-begin-with level. Any data in a spreadsheet should be committed if and only if it's going to be used in a graphic.
2. I'm not _too_ concerned about data file sizes because data files _should_ be small if they're being used in a graphic.

**Comment by erxclau** [comment]
> maybe that shouldn't be handled at the .gitignore level, but rather at the this-spreadsheet-shouldn't-have-anything-sensitive-to-begin-with level.

Maybe it'd be useful to add friction like a `pre-commit` hook.

**Comment by naitian** [comment]
Hmm yeah makes sense. Maybe a separate lambda or something that renders from a deployed graphic?

**Comment by erxclau** [comment]
Ok, I'm going to try implementing a local solution that avoids having to download a new browser.

<https://github.com/puppeteer/puppeteer#default-runtime-settings>
<https://github.com/mbalabash/find-chrome-bin>

**Comment by erxclau** [comment]
I'm going to implement the build version just for a single entry for now, but having multiple entries will complicate this slightly. We'll have to import entries from the JSON config and then loop.

**Comment by erxclau** [comment]
> generate the same image more than once and having a statically hosted image we can use elsewhere (like in a portfolio site and the README)

We'll probably want to change the file name or something if we want to automatically embed into the README.
